/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tvdgzsqrkryzqdjpqoqr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2ZGd6c3Fya3J5enFkanBxb3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMjEyMTQsImV4cCI6MjA3NTY5NzIxNH0.ccpOCcaq6Vkl1D4ozdQHU-k_zt1tjBgGrvIr6K-DfVg"